targets:
  $default:
    sources:
      - "pubspec.yaml"
      - "lib/**"
      - "node/gltf_validator.dart"
      - "tool/**"
      - "web/**"
      - "$package$"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
          - node/**.dart
        options:
          compiler: dart2js
        release_options:
          dart2js_args:
            - --minify
            - --lax-runtime-type-to-string
            - --server-mode
            - --trust-primitives
            - --omit-implicit-checks
        dev_options:
          dart2js_args:
            - --server-mode
            - -DGLTF_VALIDATOR_DEBUG=true
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        release_options:
          compiler: dart2js
          dart2js_args:
          - --minify
          - --lax-runtime-type-to-string
          - --no-source-maps
          - --trust-primitives
          - --omit-implicit-checks
          - --omit-as-casts